### ISSUE TITLE
How to run on pi2b with hdmi tv

### ISSUE THREAD

**Issue by team-5678** [elParaguayo/RPI-Info-Screen#10]
Hi I am new to using a pi but was wondering if you could tell me how to run this on my pi2b with a 1080p tv all it said in the read me was to run default.py but I don't know how to do that. I have already configured the plugins the way I want them so all I need to do is run it.

**Comment by elParaguayo** [comment]
Run `python default.py`

**Comment by team-5678** [comment]
And where do I put the files

**Comment by elParaguayo** [comment]
Wherever you like. If you just downloaded the zip file, extract it and run default.py from wherever you extracted the files.

**Comment by team-5678** [comment]
Ok thanks I will try it and then let you know how it goes

**Comment by team-5678** [comment]
i am getting this error

pi@raspberrypi:~ $ python default.py
Traceback (most recent call last):
  File "default.py", line 275, in <module>
    pluginScreens = getScreens()
  File "default.py", line 102, in getScreens
    plugin = loadPlugin(i)
  File "default.py", line 92, in loadPlugin
    return imp.load_module(MainModule, *plugin["info"])
  File "./plugins/weather/screen.py", line 4, in <module>
    import simplejson as json
ImportError: No module named simplejson

I currently only have the agenda clock tube and the whether plugins.

**Comment by elParaguayo** [comment]
This code is very old and unmaintained so there may well be bugs.

Change that line to just `import json`

**Comment by team-5678** [comment]
ok what would i need to do to make the kivi version work an a non pi screen

**Comment by elParaguayo** [comment]
Change the resolution of every screen! The layouts are tailored to a fixed resolution, but the script should work still.

**Comment by team-5678** [comment]
ok i will try that thanks
