### ISSUE TITLE
screen size - default.py

### ISSUE THREAD

**Issue by greg121** [elParaguayo/RPI-Info-Screen#6]
2) Edit default.py - Line 16 sets the screen size (this will be moved into a config file at some point)

Where to insert screen size? Line 16 doesn't seem to be correct.

**Comment by elParaguayo** [comment]
Which branch of the script are you using? The default version when you open the page on Github is for a Pi that is using the Adafruit TFT screen. If you're not using this screen then you should use the "Master" branch and edit line 17 (https://github.com/elParaguayo/RPI-Info-Screen/blob/master/default.py#L17)

**Comment by greg121** [comment]
I'm using a chinese clone of the adafruit screen. So this should work. Was just confused from the readme. Thanks for clearing things up for me.
