### ISSUE TITLE
Some remarks

### ISSUE THREAD

**Issue by retrorich75** [elParaguayo/RPI-Info-Screen#8]
Hi great tool;

Some remarks you might want to add to the readme

For the footballscores plugin, a dependency is BeautifulSoup 
to install ;
<code>
pip install beautifulsoup
</code>

For the tube plugin a dependency is simplejson
to install;
<code>
pip install simplejson
</code>

For the photos plugin a dependency is that the folder <code>/photo/</code> should exist

Having fun with my Adafruit 2.8" PiTFT - Capacitive Touch thanks!

**Comment by elParaguayo** [comment]
Thanks. It's a good point.

**Comment by team-5678** [comment]
How do I run this I am very new to this
